name: Deploy to GitHub Pages

# Roda esta aÃ§Ã£o toda vez que vocÃª envia cÃ³digo para o branch 'main'
on:
  push:
    branches: [ main ]

# PermissÃµes necessÃ¡rias para o job
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Roda em uma mÃ¡quina virtual Linux
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3 # Baixa o seu cÃ³digo para a mÃ¡quina virtual

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v3 # Instala o Node.js
        with:
          node-version: '18' # Usa a versÃ£o 18 do Node.js
          cache: 'npm'

      - name: Generate Image List ğŸ“œ
        run: node scripts/generate-list.js # RODA O NOSSO ROBÃ”!

      - name: Setup Pages ğŸ› ï¸
        uses: actions/configure-pages@v3

      - name: Upload artifact ğŸ“¦
        uses: actions/upload-pages-artifact@v2
        with:
          path: './public' # Define a pasta 'public' como a fonte do site

      - name: Deploy to GitHub Pages ğŸš€
        id: deployment
        uses: actions/deploy-pages@v2
